# Generated by Django 3.1.4 on 2020-12-20 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollApp', '0002_auto_20201219_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollquestion',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='pollquestion',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='pollquestion',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='pollquestion',
            name='numberOfOptions',
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollApp.pollquestion')),
            ],
        ),
    ]
